### ISSUE TITLE
Cannot sell items

### ISSUE THREAD

**Issue by ngajhede** [1010101110/Auctionator-classic#10]
Coming back to Classic wow from a small break, i just thought an update of the addon would fix this issue, but it seems i am not able to sell items. I can buy items, and check for undercuts as well as cancel auctions. 

When dropping items into the selling tab, it is seemingly searching for the item, but not updating the UI. If I change between "current" and "history" tabs, it updates - but I am still not able to sell, and no prices have been put in. 

I have recorded a video of the issue here: https://www.youtube.com/watch?v=2Ve9f99FFBY

I am on the OSX client.

**Comment by 1010101110** [comment]
hm it works for lots of people. something in your case is not working. 

it looks like the last thing in debug is roundPriceDown(55500,nil) i don't think that nil should happen. maybe it is causing the issue

**Comment by indyIOT** [comment]
I am having similar problems where the addon just does not work for selling. I have tried reinstalling, downloading from github. It worked before, but I just reinstalled wow and when I installed this addon it no longer works. 

Also doesnt work if I click on a price.

**Comment by brisk67** [comment]
^ Same thing going on for me.
In the "Buy" tab, the back button is missing when selecting an item.

When I drop an item in the "Sell" tab, either it doesn't search for anything or gets stuck at "page 2 out of 2". If i go from current to history it updates. Clicking a price doesn't enters in on the left and no matter the price I enter, the "create auction" button is never clickable.

This has been happening since I reinstalled the game. Disabled all other addons, clear my cache and WTF folder, had a friend of mine send me his working "auctionator" folder. Reset my game to default.

**Comment by indyIOT** [comment]
Me to a tee. Since I reinstalled auctionator sell tab is hella screwed. Never repopulates the results right, doesnt set price right. wont let me sell.

**Comment by 1010101110** [comment]
@tbandtg @brisk67 do you want to turn debug on in settings and take video or take screenshots, similar to op?

have you guys made any changes to the default settings? like the undercutting settings?

**Comment by 1010101110** [comment]
i added f598c1135eca611f6c472b2e69c1f84f36edba81 which seemed to be the last error

you can download from github directly and see if that helps?

**Comment by brisk67** [comment]
This was filmed with the latest commit being bf0242f

https://www.youtube.com/watch?v=53iMqW30r9c&

I first went to the buy tab for the missing "back" button. Then the issues with the sell tab. No other addons enabled and everything is completely default.

EDIT : Seems to be fixed - Going into "Interface options" - AddOns tab - Auctionator - Pulizia and clearing all 4 fixed the issue.

If thats of any help - Pricing history cleared. Memory went from 3011 KB to 1315 KB
Posting history cleared. Memory went from 1315 KB to 1315 KB
Stacking preferences cleared. Memory went from 1315 KB to 1315 KB
Shopping lists cleared. Memory went from 1315 KB to 1316 KB

**Comment by 1010101110** [comment]
@brisk67  thanks for the upload

so maybe some issue with the database hmmm, it's annoying there isn't some error it just never renders the auction list.

**Comment by 1010101110** [comment]
I think you all that are experiencing this have a corrupted or blank AUCTIONATOR_SAVEDVARS

it seems the code doesn't check if the AUCTIONATOR_SAVEDVARS.STARTING_DISCOUNT is nil which causes the error i think.

https://github.com/1010101110/Auctionator-classic/blob/master/Auctionator.lua#L5145-L5158

**Comment by 1010101110** [comment]
fix

https://github.com/1010101110/Auctionator-classic/commit/305cb01f9b67cecdc383b674a5492aaac84f5d67#diff-f18e221de75baa306853590e344d8c9eL5146

**Comment by indyIOT** [comment]
Fixed it for me Thanks much
