### ISSUE TITLE
zhCN文件

### ISSUE THREAD

**Issue by nanjuekaien1** [1010101110/Auctionator-classic#12]
- [ ] [zhCN.zip](https://github.com/1010101110/Auctionator-classic/files/4638244/zhCN.zip)

 AuctionatorConfig.xml

- [327 ] `<FontString inherits="GameFontNormal" text="When SHIFT is down show">`

- [334 ] `<FontString inherits="GameFontNormal" text="Show disenchanting details">`

- [ 494] ` <FontString inherits="GameFontNormal" text="Buyout Price">`

- [ 503] `<FontString inherits="GameFontNormal" text="Undercut by">`

- [ 512] ` <FontString inherits="GameFontNormal" text="Starting Price Discount">`

- [521 ] `<FontString inherits="GameFontHighlight" text="percent">`

  @1010101110 @T3rdW 
There is no way to localize these places

**Comment by 1010101110** [comment]
:D i could google translate i guess

**Comment by nanjuekaien1** [comment]
There is no way to localize these places
